# ~/.config/gtk-3.0/settings.ini
# aero-nature GTK settings

[Settings]
gtk-theme-name          = Colloid-Green-Dark
gtk-icon-theme-name     = Papirus-Dark
gtk-cursor-theme-name   = Bibata-Modern-Ice
gtk-cursor-theme-size   = 24
gtk-font-name           = Inter 11
gtk-application-prefer-dark-theme = true
gtk-button-images       = true
gtk-menu-images         = true
gtk-enable-animations   = true
